export const it = {
  nav: {
    product: "Prodotto",
    turin: "Torino",
    download: "Scarica",
    cta: "Scarica l'app",
    menu: "Menu",
  },
  common: {
    ios: "Scarica per iPhone",
    android: "Scarica per Android",
    honesty: "Prima Torino. Non inventiamo dati live che non abbiamo.",
    placeholderIos: "[iOS App Store URL]",
    placeholderAndroid: "[Android Play URL]",
    comingSoon: "In arrivo — lascia la mail",
    back: "Torna alla home",
    draft: "Bozza",
  },
  hero: {
    badge: "Torino · GTT · ZTL",
    title: "La scorciatoia per Torino.",
    sub: "Una mappa sola per auto, GTT, camminate, bici, parcheggi e ricarica. L'accesso è facoltativo.",
    search: "Cerca qui",
    modes: ["Auto", "Mezzi", "A piedi", "Bici"],
    banner: "241 m · Via Po",
    dock: "12 min · 1,7 km",
    exit: "Esci",
  },
  modes: {
    title: "Un'app invece di quattro",
    sub: "Guidare, prendere il 61, cercare posto, ricaricare. Tutto sulla stessa mappa.",
    items: [
      { name: "Auto", line: "Tempi che tengono conto della coda, traffico colorato sulle strade" },
      { name: "Mezzi", line: "Viaggi GTT completi, le corse successive come chip" },
      { name: "A piedi", line: "Guida pedonale, non un cruscotto d'auto" },
      { name: "Bici / e-bike", line: "Percorsi ciclabili e monopattini in mappa" },
      { name: "Parcheggi", line: "Parcheggi e stalli vicino a dove stai andando" },
      { name: "Ricarica", line: "Colonnine EV sulla mappa" },
    ],
  },
  stories: {
    title: "Un viaggio, tutta la città",
    sub: "Dal portone di casa al portone di arrivo, senza cambiare app.",
    a: {
      kicker: "Guida",
      title: "Guida come chi ci vive",
      body: "Turn-by-turn con ETA che tengono conto della coda, strade colorate dal traffico e alternative: la più veloce o quella con meno semafori. Se stai per entrare in ZTL, te lo diciamo prima.",
      points: ["Alternative: Più veloce / Meno semafori", "Avvisi ZTL per le zone di Torino", "Semafori con conto alla rovescia dove li abbiamo cronometrati"],
    },
    b: {
      kicker: "Mezzi",
      title: "Mezzi che dicono la verità",
      body: "Il viaggio intero: a piedi fino alla fermata, sali sul 61, scendi, e gli ultimi metri a piedi. Le corse successive sono chip grandi con i minuti. Quando il feed è orario, scriviamo orario.",
      points: ["Orari programmati etichettati come tali", "Corse successive come chip di minuti", "Se una coincidenza è a rischio, lo diciamo"],
    },
    c: {
      kicker: "A piedi",
      title: "A piedi, non in auto sul marciapiede",
      body: "Percorso teal, camera più vicina, indicazioni da pedone. Niente tachimetro, niente HUD da autostrada. D'estate puoi scegliere il percorso con più ombra.",
      points: ["18 m · Percorso pedonale", "Percorsi con la massima ombra", "Mappe offline per quando il segnale sparisce"],
    },
  },
  layers: {
    title: "I livelli della città",
    sub: "La mappa di esplorazione è la schermata principale: accendi quello che ti serve.",
    chips: ["Parcheggi", "Ricarica", "Mezzi", "Micromobilità", "Traffico", "Semafori"],
    caption: "Anteprima illustrata. In app i livelli si accendono e si spengono dalla mappa.",
  },
  account: {
    title: "L'account è facoltativo",
    sub: "La mappa funziona senza registrarsi. Punto.",
    free: {
      title: "Usala subito",
      items: ["Naviga senza account", "Cerca, guida, cammina, prendi il bus", "Nessuna registrazione per aprire la mappa"],
    },
    saved: {
      title: "Salva i tuoi posti",
      items: ["Casa, lavoro, recenti", "Profilo e preferenze sincronizzate", "Serve solo per questo"],
    },
  },
  turinBlock: {
    title: "Torino, di proposito",
    body: "Costruita per questa città: GTT, ZTL, Porta Nuova, la griglia delle vie, il Po e le colline, l'ombra d'estate. Ci stiamo allargando ai comuni vicini. Non è una mappa mondiale con Torino come spillo.",
    cta: "Perché Torino",
  },
  waitlist: {
    title: "Prendi l'app",
    sub: "Lasciaci la mail: ti mandiamo il link quando è sul tuo store.",
    email: "La tua mail",
    city: "Città",
    button: "Avvisami",
    success: "Ti mandiamo il link quando è sul tuo store.",
    error: "Serve una mail valida.",
    note: "Niente spam, niente rivendita dei tuoi dati.",
  },
  faq: {
    title: "Domande",
    items: [
      { q: "È gratis?", a: "Usare la mappa sì. L'account è facoltativo e serve solo per i posti salvati." },
      { q: "Funziona senza account?", a: "Sì. Apri l'app e navighi. L'accesso serve solo per salvare posti e sincronizzare il profilo." },
      { q: "Gli orari del bus sono live?", a: "Quando il realtime GTT è fresco mostriamo il dato live; altrimenti lo etichettiamo come programmato. In più facciamo previsioni per dare un tempo più accurato." },
      { q: "Mostrate i secondi al verde?", a: "Solo ai semafori che abbiamo cronometrato davvero. Altrove non facciamo finta." },
      { q: "Vedo i posti liberi per parcheggiare?", a: "Sì: occupazione live degli stalli su strada e capienza dei parcheggi, e ti diciamo se l'auto ci sta nello stallo." },
      { q: "Dove funziona?", a: "Torino e i comuni vicini, per cominciare." },
    ],
  },
  footer: {
    tagline: "La scorciatoia per Torino.",
    product: "Prodotto",
    legal: "Legale",
    made: "Fatta per Torino",
    rights: "Tutti i diritti riservati.",
  },
  features: {
    title: "Cosa fa Shortcut",
    sub: "Il dettaglio, con i limiti scritti accanto. Preferiamo dire cosa non sappiamo.",
    constraintLabel: "Limite",
    items: [
      {
        name: "Guida",
        body: "Turn-by-turn con ETA consapevoli della coda, strade colorate dal traffico, alternative fra la più veloce e quella con meno semafori, avvisi ZTL prima di entrare.",
        constraint: "Il traffico dipende dai dati che riceviamo: dove la copertura è scarsa, l'ETA resta una stima.",
      },
      {
        name: "Mezzi (GTT)",
        body: "Viaggio completo: a piedi, salita, tratta, discesa, a piedi. Corse successive come chip di minuti, con l'ora di aggiornamento del feed.",
        constraint: "Se il feed è programmato, scriviamo programmato. Non mostriamo mai un arrivo live inventato.",
      },
      {
        name: "A piedi",
        body: "Camera più vicina, percorso teal, indicazioni pedonali brevi, niente HUD da auto. Con l'opzione percorso più ombreggiato d'estate.",
        constraint: "L'ombra è calcolata su edifici e alberi mappati: dove il dato manca, il percorso resta quello standard.",
      },
      {
        name: "Parcheggi",
        body: "Parcheggi vicino alla destinazione, capienza live dei parcheggi in struttura, occupazione live degli stalli su strada e una risposta secca: l'auto ci sta o no.",
        constraint: "La capienza dei parcheggi la mostriamo quando la città la pubblica.",
      },
      {
        name: "Ricarica",
        body: "Colonnine EV sulla mappa, come livello attivabile insieme al resto.",
        constraint: "Disponibilità e stato dipendono da chi gestisce la colonnina.",
      },
      {
        name: "Micromobilità",
        body: "Monopattini e bici in sharing (per esempio Dott) sulla stessa mappa, senza saltare da un'app all'altra.",
        constraint: "Mostriamo gli operatori che ci danno un feed. Noleggio e sblocco restano nella loro app.",
      },
      {
        name: "Offline",
        body: "Mappe offline scaricabili: la città resta consultabile anche senza rete.",
        constraint: "Offline non c'è traffico né realtime: sono dati che arrivano dalla rete.",
      },
      {
        name: "Semafori",
        body: "Semafori sul percorso con conto alla rovescia e secondi al verde.",
        constraint: "Solo agli incroci che abbiamo cronometrato. Gli altri restano semafori normali.",
      },
    ],
  },
  turinPage: {
    title: "Torino, non «una città qualsiasi»",
    sub: "Il 61 che passa, la ZTL che si accende, il Po sotto i ponti, la collina dietro. Shortcut nasce qui.",
    body1:
      "Muoversi a Torino è un mestiere: la griglia delle vie è generosa, ma i portici, la ZTL, i cantieri e gli orari GTT decidono davvero come va la giornata. Da Porta Nuova a Piazza Castello cambi tre modi in dieci minuti, e oggi lo fai con tre app diverse.",
    body2:
      "Shortcut mette drive, GTT, piedi, bici, parcheggi e ricarica sulla stessa mappa, con le regole di questa città dentro: la ZTL, i lungofiume, le salite verso la collina, e d'estate l'ombra come criterio vero per scegliere un percorso a piedi.",
    honestyTitle: "Come restiamo onesti sui dati",
    honestyCols: ["Dato", "Cosa mostra Shortcut"],
    honestyRows: [
      ["Traffico live", "Sì, sui percorsi in auto"],
      ["Arrivi GTT", "Live quando il feed è live, altrimenti programmati"],
      ["Conto alla rovescia semafori", "Solo dove li abbiamo cronometrati"],
      ["Posti liberi nei parcheggi", "Quando la città li pubblica"],
      ["Occupazione stalli su strada", "Sì"],
    ],
    expand: "Torino prima, poi i comuni vicini. Una città europea alla volta, fatta bene.",
  },
  downloadPage: {
    title: "Scarica Shortcut",
    sub: "iPhone e Android. L'account è facoltativo: apri e naviga.",
    qr: "[QR code placeholder]",
    qrNote: "Inquadra per aprire la pagina di download.",
    reqTitle: "Requisiti",
    req: ["iPhone con iOS recente", "Telefono Android recente", "GPS attivo per la navigazione", "Mappe offline scaricabili per usarla senza rete"],
  },
  privacy: {
    title: "Privacy",
    updated: "Bozza — ultimo aggiornamento: agosto 2026",
    sections: [
      { h: "In breve", p: "La posizione serve a navigare. Non vendiamo la tua posizione a reti pubblicitarie. L'account è facoltativo." },
      { h: "Accesso facoltativo", p: "Puoi usare la mappa e navigare senza registrarti. Se crei un account, serve solo per posti salvati, profilo e sincronizzazione fra dispositivi." },
      { h: "Posizione", p: "Usiamo la posizione del dispositivo per mostrarti dove sei, calcolare percorsi e dare indicazioni. In navigazione la posizione viene usata in tempo reale sul dispositivo e per calcolare il percorso." },
      { h: "Cosa non facciamo", p: "Non vendiamo dati di posizione a inserzionisti o data broker. Non costruiamo profili pubblicitari con i tuoi spostamenti." },
      { h: "Dati di terze parti", p: "Mostriamo dati di trasporto, parcheggi, ricarica e sharing forniti da operatori e dalla città. Quando un dato è programmato e non live, lo etichettiamo." },
      { h: "Cancellazione", p: "Puoi cancellare l'account e i posti salvati dall'app. Scrivici e ti aiutiamo." },
    ],
  },
  terms: {
    title: "Termini",
    updated: "Bozza — ultimo aggiornamento: agosto 2026",
    sections: [
      { h: "Uso del servizio", p: "Shortcut è un'app di navigazione. Puoi usarla per muoverti in città, senza account o con un account gratuito." },
      { h: "Guida con la testa", p: "Le indicazioni sono un supporto, non un ordine. Rispetta il codice della strada, la segnaletica e le limitazioni ZTL: la responsabilità di come guidi o cammini resta tua." },
      { h: "Accuratezza dei dati", p: "Facciamo il possibile perché mappe, orari e disponibilità siano corretti, e diciamo quando un dato è programmato invece che live. Non possiamo garantire che ogni informazione sia sempre esatta." },
      { h: "Account", p: "Se crei un account, sei responsabile delle credenziali. Puoi chiuderlo quando vuoi." },
      { h: "Modifiche", p: "Il servizio evolve: funzioni e coperture possono cambiare. Le modifiche rilevanti a questi termini le comunichiamo nell'app." },
    ],
  },
  notFound: {
    title: "Strada senza uscita",
    sub: "Questa pagina non esiste. Ricalcolo del percorso…",
  },
};

export type Copy = typeof it;

export const en: Copy = {
  nav: { product: "Product", turin: "Turin", download: "Download", cta: "Get the app", menu: "Menu" },
  common: {
    ios: "Download for iPhone",
    android: "Download for Android",
    honesty: "Turin first. We don't invent live data we don't have.",
    placeholderIos: "[iOS App Store URL]",
    placeholderAndroid: "[Android Play URL]",
    comingSoon: "Coming soon — join the list",
    back: "Go home",
    draft: "Draft",
  },
  hero: {
    badge: "Turin · GTT · ZTL",
    title: "The shortcut through Turin.",
    sub: "One map for driving, GTT, walking, bikes, parking and charging. Sign-in optional.",
    search: "Search here",
    modes: ["Drive", "Transit", "Walk", "Bike"],
    banner: "241 m · Via Po",
    dock: "12 min · 1.7 km",
    exit: "Exit",
  },
  modes: {
    title: "One app instead of four",
    sub: "Drive, catch the 61, find a space, plug in. Same map.",
    items: [
      { name: "Drive", line: "Jam-aware times, traffic on the streets" },
      { name: "Transit", line: "Full GTT trips, later buses as chips" },
      { name: "Walk", line: "Pedestrian guidance, not a car HUD" },
      { name: "Bike / e-bike", line: "Cycle routes and scooters on the map" },
      { name: "Parking", line: "Car parks and bays near where you're going" },
      { name: "Charging", line: "EV chargers on the map" },
    ],
  },
  stories: {
    title: "One trip, the whole city",
    sub: "Door to door without switching apps.",
    a: {
      kicker: "Drive",
      title: "Drive like you live here",
      body: "Turn-by-turn with jam-aware ETAs, traffic-coloured streets and alternatives: fastest, or fewer lights. If you're about to enter a ZTL, we tell you before you do.",
      points: ["Alternatives: Fastest / Fewer lights", "ZTL warnings for Turin's limited-traffic zones", "Traffic-light countdowns where we've timed them"],
    },
    b: {
      kicker: "Transit",
      title: "Transit that tells the truth",
      body: "The whole trip: walk to the stop, board line 61, ride, walk the last bit. Later departures are big minute chips. When the feed is scheduled, we write scheduled.",
      points: ["Scheduled times labelled as scheduled", "Later departures as minute chips", "If a connection is at risk, we say so"],
    },
    c: {
      kicker: "Walk",
      title: "Walk, don't drive a sidewalk",
      body: "Teal path, closer camera, pedestrian prompts. No speedometer, no motorway HUD. In summer you can take the route with the most shade.",
      points: ["18 m · Footpath", "Routes with maximum shade", "Offline maps for when signal drops"],
    },
  },
  layers: {
    title: "Layers of the city",
    sub: "The explore map is the home screen: switch on what you need.",
    chips: ["Parking", "Charging", "Transit", "Micromobility", "Traffic", "Signals"],
    caption: "Illustrated preview. In the app, layers toggle straight on the map.",
  },
  account: {
    title: "The account is optional",
    sub: "The map works without signing up. That's it.",
    free: {
      title: "Use it now",
      items: ["Navigate with no account", "Search, drive, walk, take the bus", "No sign-up to open the map"],
    },
    saved: {
      title: "Save your places",
      items: ["Home, work, recents", "Profile and preferences synced", "That's all it's for"],
    },
  },
  turinBlock: {
    title: "Turin, on purpose",
    body: "Built for this city: GTT, ZTL, Porta Nuova, the street grid, the Po and the hills, summer shade. We're expanding to nearby towns. Not a worldwide generic map with Torino as a pin.",
    cta: "Why Turin",
  },
  waitlist: {
    title: "Get the app",
    sub: "Leave your email and we'll send the link when it's on your store.",
    email: "Your email",
    city: "City",
    button: "Notify me",
    success: "We'll send the link when it's on your store.",
    error: "We need a valid email.",
    note: "No spam, no reselling your data.",
  },
  faq: {
    title: "Questions",
    items: [
      { q: "Is it free?", a: "Using the map is. The account is optional and only exists for saved places." },
      { q: "Does it work without an account?", a: "Yes. Open it and navigate. Sign-in is only for saved places and syncing your profile." },
      { q: "Is bus time live?", a: "When GTT realtime is fresh we show it live; otherwise we label it scheduled. We also make predictions to give you a more accurate time." },
      { q: "Do you show seconds-to-green?", a: "Only at lights we've actually timed. Elsewhere we don't pretend." },
      { q: "Do you show free parking spaces?", a: "Yes: live curb occupancy and car-park capacity, plus whether your car actually fits the spot." },
      { q: "Where does it work?", a: "Turin and nearby towns first." },
    ],
  },
  footer: {
    tagline: "The shortcut through Turin.",
    product: "Product",
    legal: "Legal",
    made: "Made for Torino",
    rights: "All rights reserved.",
  },
  features: {
    title: "What Shortcut does",
    sub: "The detail, with the limits written next to it. We'd rather say what we don't know.",
    constraintLabel: "Constraint",
    items: [
      {
        name: "Drive",
        body: "Turn-by-turn with jam-aware ETAs, traffic-coloured streets, alternatives between fastest and fewer lights, and ZTL warnings before you cross the line.",
        constraint: "Traffic depends on the data we receive: where coverage is thin, the ETA stays an estimate.",
      },
      {
        name: "Transit (GTT)",
        body: "The full trip: walk, board, ride, alight, walk. Later departures as minute chips, with the time the feed was last updated.",
        constraint: "If the feed is scheduled, we write scheduled. We never show an invented live arrival.",
      },
      {
        name: "Walk",
        body: "Closer camera, teal path, short pedestrian prompts, no car HUD. With a most-shade option for summer.",
        constraint: "Shade is computed from mapped buildings and trees: where that data is missing, you get the standard route.",
      },
      {
        name: "Parking",
        body: "Car parks near your destination, live car-park capacity, live curb occupancy for street bays, and a straight answer on whether your car fits the spot.",
        constraint: "Car-park capacity shows up when the city publishes it.",
      },
      {
        name: "Charging",
        body: "EV chargers on the map, as a layer you switch on next to everything else.",
        constraint: "Availability and status depend on the charge point operator.",
      },
      {
        name: "Micromobility",
        body: "Shared scooters and bikes (Dott, for example) on the same map, without hopping between apps.",
        constraint: "We show operators that give us a feed. Renting and unlocking stay in their app.",
      },
      {
        name: "Offline",
        body: "Downloadable offline maps: the city stays usable with no connection.",
        constraint: "Offline there's no traffic and no realtime — those come over the network.",
      },
      {
        name: "Signals",
        body: "Traffic lights on your route with a countdown and seconds-to-green.",
        constraint: "Only at junctions we've timed. The rest stay ordinary traffic lights.",
      },
    ],
  },
  turinPage: {
    title: "Turin, not \u00absome city\u00bb",
    sub: "The 61 pulling in, the ZTL switching on, the Po under the bridges, the hill behind. Shortcut starts here.",
    body1:
      "Getting around Turin is a craft: the grid is generous, but the porticoes, the ZTL, the roadworks and GTT timetables decide how your day actually goes. From Porta Nuova to Piazza Castello you switch modes three times in ten minutes — and today you do it with three apps.",
    body2:
      "Shortcut puts drive, GTT, walking, bikes, parking and charging on one map, with this city's rules inside it: the ZTL, the riverside, the climb to the hills, and in summer, shade as a real reason to pick a walking route.",
    honestyTitle: "How we stay honest with city data",
    honestyCols: ["Thing", "What Shortcut shows"],
    honestyRows: [
      ["Live traffic", "Yes, on drive routes"],
      ["GTT arrivals", "Live when the feed is live; else scheduled"],
      ["Traffic-light countdown", "Only where timed"],
      ["Car-park free spaces", "When the city publishes them"],
      ["Street-bay occupancy", "Yes"],
    ],
    expand: "Turin first, then nearby towns. One European city at a time, done properly.",
  },
  downloadPage: {
    title: "Download Shortcut",
    sub: "iPhone and Android. The account is optional: open it and navigate.",
    qr: "[QR code placeholder]",
    qrNote: "Scan to open the download page.",
    reqTitle: "Requirements",
    req: ["iPhone on a recent iOS", "Recent Android phone", "Location on for navigation", "Offline maps downloadable for no-signal use"],
  },
  privacy: {
    title: "Privacy",
    updated: "Draft — last updated: August 2026",
    sections: [
      { h: "In short", p: "Location is used to navigate. We don't sell your location to ad networks. The account is optional." },
      { h: "Optional sign-in", p: "You can use the map and navigate without registering. If you create an account, it only powers saved places, your profile and syncing across devices." },
      { h: "Location", p: "We use device location to show where you are, compute routes and give guidance. During navigation, location is used live on the device and to compute the route." },
      { h: "What we don't do", p: "We don't sell location data to advertisers or data brokers. We don't build ad profiles out of your movements." },
      { h: "Third-party data", p: "We show transport, parking, charging and sharing data provided by operators and the city. When a value is scheduled rather than live, we label it." },
      { h: "Deletion", p: "You can delete your account and saved places from the app. Write to us and we'll help." },
    ],
  },
  terms: {
    title: "Terms",
    updated: "Draft — last updated: August 2026",
    sections: [
      { h: "Using the service", p: "Shortcut is a navigation app. You can use it to move around the city, with or without a free account." },
      { h: "Use your head", p: "Guidance is support, not an order. Follow the road rules, the signage and ZTL restrictions: how you drive or walk stays your responsibility." },
      { h: "Data accuracy", p: "We work hard to keep maps, times and availability correct, and we say when something is scheduled rather than live. We can't guarantee every value is always exact." },
      { h: "Accounts", p: "If you create an account, you're responsible for your credentials. You can close it whenever you like." },
      { h: "Changes", p: "The service evolves: features and coverage can change. We'll flag meaningful changes to these terms in the app." },
    ],
  },
  notFound: { title: "Dead end", sub: "This page doesn't exist. Recalculating route…" },
};
