export const it = {
  nav: {
    product: "Prodotto",
    cities: "Città",
    waitlist: "Lista d'attesa",
    cta: "Entra in lista",
    menu: "Menu",
  },
  common: {
    ios: "App Store",
    android: "Google Play",
    comingSoon: "Lancio il mese prossimo",
    back: "Torna alla home",
    joinWaitlist: "Entra in lista d'attesa",
    seeFeatures: "Scopri le funzioni",
  },
  hero: {
    badge: "In arrivo a Torino",
    title: "La scorciatoia per",
    titleAccent: "attraversare Torino",
    sub: "Parcheggio, mezzi e traffico in una sola app.",
    ctaPrimary: "Entra in lista d'attesa",
    ctaSecondary: "Guarda cosa fa",
    proof: ["Parcheggi live", "Mezzi più precisi", "Ricarica EV", "Assistente vocale"],
    stats: [
      { value: "1", label: "app invece di quattro" },
      { value: "-9 min", label: "medi persi a cercare posto" },
      { value: "24/7", label: "traffico e disservizi" },
    ],
  },
  scene: {
    billboard: "Lancio il mese prossimo",
    awning: "Live a Torino",
    shelter: "Torino + cintura",
    light: "Verde tra 12 s",
    parkTitle: "Via Roma",
    parkBody: "2 posti liberi · la tua auto ci sta",
    transitTitle: "Coincidenza a rischio",
    transitBody: "Nuovo percorso: 4 → 15, +2 min",
  },

  pillars: {
    title: "Quattro cose, fatte bene",
    sub: "Il resto della città lo trovi comunque sulla stessa mappa.",
    items: [
      {
        key: "parking",
        name: "Parcheggio, davvero",
        body: "Stalli su strada e parcheggi coperti con disponibilità live vicino alla tua destinazione. E ti diciamo se la tua auto ci sta.",
      },
      {
        key: "transit",
        name: "Mezzi più precisi",
        body: "Previsioni di arrivo corrette sul campo, non solo l'orario teorico. Se la coincidenza salta, ti proponiamo subito l'alternativa.",
      },
      {
        key: "drive",
        name: "Guida intelligente",
        body: "Traffico live, conto alla rovescia dei semafori sul percorso e colonnine di ricarica per chi va in elettrico.",
      },
      {
        key: "voice",
        name: "Parla con l'app",
        body: "Chiedi, cambia destinazione, aggiungi una tappa. Senza toccare lo schermo mentre guidi.",
      },
    ],
  },
  parking: {
    kicker: "Parcheggio",
    title: "Smetti di girare in tondo",
    body: "Mentre ti avvicini, Shortcut cerca in parallelo lo stallo su strada più vicino e il parcheggio in struttura con posti liberi. Confronta prezzo, distanza a piedi e disponibilità in tempo reale.",
    points: [
      "Stalli su strada con probabilità di posto libero",
      "Parcheggi coperti con posti liberi aggiornati",
      "Controllo misure: la tua auto entra o no",
      "Navigazione fino allo stallo, non solo all'indirizzo",
    ],
  },
  transit: {
    kicker: "Mezzi pubblici",
    title: "Orari che reggono nel mondo reale",
    body: "Uniamo i dati dell'azienda di trasporto con quello che succede davvero in strada. Se il tuo autobus è in ritardo o quello dopo è in anticipo, lo sappiamo prima di te.",
    points: [
      "Arrivi corretti, non solo programmati",
      "Coincidenza a rischio? Nuovo percorso in un tocco",
      "Fermate chiuse, deviazioni e scioperi in mappa",
      "Pianificazione porta a porta, a piedi compreso",
    ],
  },
  drive: {
    kicker: "Guida",
    title: "Il verde, il traffico, la ricarica",
    body: "Conto alla rovescia dei semafori sul tuo percorso, code segnalate prima di entrarci, colonnine con potenza e disponibilità se guidi elettrico.",
    points: [
      "Countdown semafori sugli incroci mappati",
      "Traffico e incidenti in tempo reale",
      "Colonnine EV filtrate per presa e potenza",
      "Alternative: più veloce o meno semafori",
    ],
  },
  voice: {
    kicker: "Assistente",
    title: "Chiedi, e basta",
    sub: "Un assistente che conosce il tuo viaggio in corso.",
    lines: [
      "«Trovami un parcheggio coperto vicino all'arrivo»",
      "Tre parcheggi entro 300 m. Il migliore ha 42 posti liberi, 2,00 €/h.",
      "«Aggiungi una tappa alla ricarica»",
      "Aggiunta. Arrivi 6 minuti dopo, con l'80% di batteria.",
    ],
  },
  more: {
    title: "E tutto il resto della città",
    sub: "Meno app aperte, meno tempo perso.",
    items: [
      { name: "Traffico live", body: "Code, cantieri e incidenti aggiornati in continuo." },
      { name: "Disservizi", body: "Fermata chiusa, linea deviata, ascensore rotto: lo dici tu, lo diciamo noi." },
      { name: "Micromobilità", body: "Monopattini e bike sharing sulla stessa mappa." },
      { name: "A piedi", body: "Percorsi pedonali reali, scale e attraversamenti inclusi." },
      { name: "Offline", body: "La mappa della città resta consultabile senza rete." },
      { name: "Privacy", body: "Account facoltativo. La mappa funziona anche senza." },
    ],
  },
  how: {
    title: "Come funziona",
    steps: [
      { n: "01", name: "Dì dove vai", body: "Indirizzo, luogo salvato o richiesta vocale." },
      { n: "02", name: "Scegli il modo", body: "Auto, mezzi, a piedi o misto: Shortcut confronta tempo, costo e attesa." },
      { n: "03", name: "Arriva e parcheggia", body: "Ti seguiamo fino allo stallo o fino alla fermata giusta." },
    ],
  },
  cities: {
    kicker: "Dove siamo",
    title: "Si parte da Torino",
    body: "Torino e i comuni della cintura sono la nostra prima città: dati locali, regole locali, mezzi locali. Poi arriviamo altrove.",
    cta: "Vedi il piano città",
  },
  waitlist: {
    title: "Entra nella lista d'attesa",
    sub: "Lancio il mese prossimo. Ti scriviamo il giorno in cui l'app è scaricabile.",
    email: "La tua email",
    city: "La tua città",
    button: "Avvisami al lancio",
    success: "Ci sei. Ti scriviamo al lancio.",
    duplicate: "Sei già in lista. A presto.",
    error: "Inserisci un'email valida.",
    failed: "Qualcosa è andato storto. Riprova.",
    consent: "Acconsento a ricevere un'email quando Shortcut è disponibile.",
    note: "Niente spam. Cancellazione con un clic.",
    storeNote: "App Store e Google Play al lancio",
  },
  faq: {
    title: "Domande frequenti",
    items: [
      { q: "Quando esce Shortcut?", a: "Il lancio è previsto il mese prossimo su iOS e Android. Chi è in lista d'attesa riceve il link per primo." },
      { q: "Quanto costa?", a: "Le funzioni di navigazione, mezzi e parcheggio di base sono gratuite. Alcune funzioni avanzate saranno in abbonamento." },
      { q: "Da dove arrivano i dati sui parcheggi?", a: "Da operatori dei parcheggi, sensori e dati aperti delle città, uniti a modelli nostri per gli stalli su strada." },
      { q: "Serve un account?", a: "No. L'account serve solo per salvare i luoghi e sincronizzare le preferenze." },
      { q: "Cosa fate dei miei dati?", a: "Il minimo indispensabile per farti navigare. Nessuna rivendita dei dati personali. Trovi tutto nella privacy policy." },
      { q: "Chi c'è dietro Shortcut?", a: "Shortcut è un'app di Civimatica, che lavora su dati e mobilità urbana." },
    ],
  },
  cta: {
    title: "Pronto a prendere la scorciatoia?",
    sub: "Lascia l'email: ti avvisiamo appena l'app è sugli store.",
  },
  footer: {
    tagline: "Una sola app per muoverti in città: parcheggio, mezzi, guida e ricarica.",
    product: "Prodotto",
    company: "Azienda",
    legal: "Legale",
    byline: "Shortcut è un'app di",
    rights: "Tutti i diritti riservati.",
    company_site: "civimatica.com",
  },
  cookies: {
    title: "Cookie e privacy",
    body: "Usiamo cookie tecnici necessari al sito e, solo con il tuo consenso, cookie di analisi per capire cosa funziona.",
    accept: "Accetta tutto",
    reject: "Solo necessari",
    more: "Privacy policy",
  },
  featuresPage: {
    title: "Tutto quello che fa Shortcut",
    sub: "Una mappa sola per parcheggio, mezzi, guida, ricarica e micromobilità.",
    items: [
      { name: "Parcheggio su strada", body: "Zone con probabilità di stallo libero, regole e tariffe, navigazione fino al punto." },
      { name: "Parcheggi in struttura", body: "Posti liberi live, prezzo orario, altezza massima e distanza a piedi dall'arrivo." },
      { name: "Misure auto", body: "Salvi la tua auto una volta: lunghezza, larghezza, altezza. Ti mostriamo solo dove entra." },
      { name: "Arrivi mezzi corretti", body: "Previsioni basate su dati reali del veicolo, non solo sul quadro orario." },
      { name: "Coincidenze protette", body: "Se stai per perdere la coincidenza ti proponiamo il piano B prima di scendere." },
      { name: "Disservizi", body: "Fermate chiuse, deviazioni, linee sospese: segnalazioni ufficiali e della community." },
      { name: "Semafori con countdown", body: "Secondi al verde sugli incroci che abbiamo mappato lungo il percorso." },
      { name: "Traffico live", body: "Colori sulle strade, incidenti e code, con ricalcolo del percorso." },
      { name: "Ricarica EV", body: "Colonnine per presa, potenza, operatore e disponibilità, anche come tappa." },
      { name: "Assistente vocale", body: "Chiedi informazioni e modifica il viaggio parlando, anche in guida." },
      { name: "Micromobilità", body: "Monopattini e bici in sharing sulla stessa mappa." },
      { name: "Offline", body: "Mappa cittadina consultabile senza connessione." },
    ],
    chips: ["2 posti liberi", "Verde tra 12 s", "Coincidenza salva"],
    lights: {
      kicker: "Semafori",
      title: "Sai quanto manca al verde",
      body: "Sugli incroci che abbiamo mappato ti mostriamo i secondi che mancano al verde: riparti più morbido, freni meno all'ultimo e consumi meno.",
      points: [
        "Countdown sugli incroci mappati",
        "Consiglio di velocità per prendere l'onda verde",
        "Meno frenate brusche in coda",
        "Funziona anche con lo schermo in tasca, a voce",
      ],
    },
    ev: {
      kicker: "Ricarica",
      title: "La colonnina giusta, non la più vicina",
      body: "Filtriamo le colonnine per presa, potenza e operatore, e ti diciamo se sono libere adesso. Puoi aggiungerle al viaggio come tappa, con l'autonomia stimata all'arrivo.",
      points: [
        "Disponibilità e potenza reale della colonnina",
        "Tappa di ricarica dentro al percorso",
        "Stima di batteria all'arrivo",
        "Parcheggio e ricarica confrontati insieme",
      ],
    },
    closing: {
      title: "Una mappa sola, tutta la città",
      body: "Entra in lista: ti scriviamo il giorno in cui Shortcut è scaricabile.",
    },
  },

  citiesPage: {
    title: "Prima Torino, poi le altre",
    sub: "Costruiamo città per città, con i dati di ognuna.",
    body: "Muoversi a Torino significa griglia di vie, ZTL, portici, colline e una rete di mezzi che va letta bene. Partiamo da qui perché è la città che conosciamo meglio, poi replichiamo il modello.",
    statusTitle: "Stato città",
    statusCols: ["Città", "Stato"],
    rows: [
      ["Torino", "Prima città al lancio"],
      ["Cintura torinese", "Al lancio"],
      ["Milano", "In preparazione"],
      ["Altre città italiane", "Su richiesta"],
    ],
    askTitle: "Vuoi Shortcut nella tua città?",
    askBody: "Scrivi la tua città nella lista d'attesa: le richieste decidono l'ordine.",
  },
  downloadPage: {
    title: "Shortcut sta arrivando",
    sub: "Lancio il mese prossimo su iPhone e Android. Entra in lista e sei tra i primi a provarla.",
    storesTitle: "Presto sugli store",
    reqTitle: "Cosa ti serve",
    req: ["iPhone con iOS 16 o successivo", "Android 10 o successivo", "Posizione attiva durante la navigazione", "Account facoltativo"],
    chips: ["Lancio il mese prossimo", "Prima Torino", "Niente spam"],
    dayOne: {
      title: "Cosa succede quando entri in lista",
      items: [
        { name: "Il link, il primo giorno", body: "Una sola email quando l'app è sugli store. Nessuna newsletter travestita." },
        { name: "La tua città conta", body: "Le città indicate nella lista decidono l'ordine con cui apriamo dopo Torino." },
        { name: "Niente spam", body: "Email e città, nient'altro. Cancellazione con un clic, sempre." },
      ],
    },
    steps: {
      title: "Come arriviamo al lancio",
      items: [
        { n: "01", name: "Torino per prima", body: "Dati locali, ZTL, parcheggi e rete GTT: la città che conosciamo meglio." },
        { n: "02", name: "La cintura, subito dopo", body: "I comuni intorno entrano con la stessa mappa e gli stessi dati." },
        { n: "03", name: "Le altre città", body: "Apriamo dove le richieste sono più forti. Fuori Torino non siamo ancora live, e lo diciamo." },
      ],
    },
    closing: {
      title: "Ci vediamo al lancio",
      body: "Un'email, il link per scaricare, e la città in tasca.",
    },
  },

  privacy: {
    title: "Privacy policy",
    updated: "Ultimo aggiornamento: agosto 2026",
    intro:
      "Shortcut è un'app di Civimatica. Questa pagina spiega in modo semplice quali dati trattiamo su questo sito e nell'app.",
    sections: [
      { h: "Dati che raccogliamo dal sito", p: "Se entri nella lista d'attesa salviamo email, città indicata e data di iscrizione. Nient'altro." },
      { h: "Perché", p: "Solo per avvisarti al lancio e capire in quali città partire. Non vendiamo i tuoi dati." },
      { h: "Cookie", p: "Cookie tecnici necessari al funzionamento; cookie di analisi solo dopo il tuo consenso, revocabile in qualsiasi momento." },
      { h: "Posizione nell'app", p: "La posizione serve alla navigazione ed è usata sul dispositivo per calcolare il percorso. Puoi usare la mappa senza account." },
      { h: "I tuoi diritti (GDPR)", p: "Puoi chiedere accesso, rettifica, cancellazione o portabilità dei tuoi dati, e opporti al trattamento. Rispondiamo entro 30 giorni." },
      { h: "Contatti", p: "Titolare del trattamento: Civimatica. Scrivi a privacy@civimatica.com per qualsiasi richiesta." },
    ],
  },
  terms: {
    title: "Termini di servizio",
    updated: "Ultimo aggiornamento: agosto 2026",
    intro: "Termini d'uso del sito shortcut e della lista d'attesa, gestiti da Civimatica.",
    sections: [
      { h: "Il servizio", p: "Shortcut è un'app di navigazione urbana. Questo sito presenta il prodotto e raccoglie iscrizioni alla lista d'attesa." },
      { h: "Uso corretto", p: "Non usare il sito per attività illecite, invio massivo di iscrizioni o tentativi di accesso non autorizzato." },
      { h: "Informazioni sul prodotto", p: "Funzioni e date di lancio possono cambiare. Le informazioni su questo sito non costituiscono impegno contrattuale." },
      { h: "Responsabilità", p: "Rispetta sempre il codice della strada. Le indicazioni dell'app sono un supporto, non un obbligo di manovra." },
      { h: "Contatti", p: "Per qualsiasi domanda: hello@civimatica.com." },
    ],
  },
  notFound: { title: "Pagina non trovata", sub: "Abbiamo perso questa scorciatoia." },
};

export type Copy = typeof it;

export const en: Copy = {
  nav: {
    product: "Product",
    cities: "Cities",
    waitlist: "Waitlist",
    cta: "Join waitlist",
    menu: "Menu",
  },
  common: {
    ios: "App Store",
    android: "Google Play",
    comingSoon: "Launching next month",
    back: "Back home",
    joinWaitlist: "Join the waitlist",
    seeFeatures: "See the features",
  },
  hero: {
    badge: "Coming to Turin",
    title: "The shortcut across",
    titleAccent: "Turin",
    sub: "Parking, transit and traffic in one app.",
    ctaPrimary: "Join the waitlist",
    ctaSecondary: "See what it does",
    proof: ["Live parking", "Sharper transit", "EV charging", "Voice assistant"],
    stats: [
      { value: "1", label: "app instead of four" },
      { value: "-9 min", label: "average time hunting for parking" },
      { value: "24/7", label: "traffic and disruptions" },
    ],
  },
  scene: {
    billboard: "Launching next month",
    awning: "Live in Turin",
    shelter: "Turin + metro area",
    light: "Green in 12 s",
    parkTitle: "Via Roma",
    parkBody: "2 spots free · your car fits",
    transitTitle: "Connection at risk",
    transitBody: "New route: 4 → 15, +2 min",
  },

  pillars: {
    title: "Four things, done properly",
    sub: "The rest of the city is on the same map anyway.",
    items: [
      {
        key: "parking",
        name: "Parking that works",
        body: "Curbside spots and garages with live availability next to where you're going. And we tell you if your car actually fits.",
      },
      {
        key: "transit",
        name: "Sharper transit",
        body: "Arrival predictions corrected against reality, not just the timetable. If your connection breaks, we hand you the alternative.",
      },
      {
        key: "drive",
        name: "Smarter driving",
        body: "Live traffic, traffic-light countdowns along your route, and EV chargers when you drive electric.",
      },
      {
        key: "voice",
        name: "Talk to the app",
        body: "Ask, change destination, add a stop. Without touching the screen while you drive.",
      },
    ],
  },
  parking: {
    kicker: "Parking",
    title: "Stop circling the block",
    body: "As you approach, Shortcut searches the nearest curbside spot and the nearest garage with free spaces in parallel. Compare price, walking distance and live availability.",
    points: [
      "Curbside spots with likelihood of a free space",
      "Garages with live free-space counts",
      "Dimension check: does your car fit?",
      "Guidance to the spot, not just the address",
    ],
  },
  transit: {
    kicker: "Public transport",
    title: "Times that hold up in the real world",
    body: "We blend operator data with what's actually happening on the street. If your bus is late or the next one is early, we know before you do.",
    points: [
      "Corrected arrivals, not just scheduled ones",
      "Connection at risk? New route in one tap",
      "Closed stops, diversions and strikes on the map",
      "Door-to-door planning, walking included",
    ],
  },
  drive: {
    kicker: "Driving",
    title: "The green light, the jam, the charger",
    body: "Traffic-light countdowns along your route, queues flagged before you hit them, chargers with power and availability if you drive electric.",
    points: [
      "Traffic-light countdowns on mapped junctions",
      "Real-time traffic and incidents",
      "EV chargers filtered by plug and power",
      "Alternatives: fastest or fewest lights",
    ],
  },
  voice: {
    kicker: "Assistant",
    title: "Just ask",
    sub: "An assistant that knows the trip you're on.",
    lines: [
      "\u201cFind me a garage near the destination\u201d",
      "Three garages within 300 m. Best one has 42 free spaces, \u20ac2.00/h.",
      "\u201cAdd a charging stop\u201d",
      "Added. You arrive 6 minutes later, at 80% battery.",
    ],
  },
  more: {
    title: "And the rest of the city",
    sub: "Fewer apps open, less time lost.",
    items: [
      { name: "Live traffic", body: "Queues, roadworks and incidents, updated continuously." },
      { name: "Disruptions", body: "Closed stop, diverted line, broken lift: you report it, we spread it." },
      { name: "Micromobility", body: "Scooters and bike share on the same map." },
      { name: "Walking", body: "Real pedestrian routes, stairs and crossings included." },
      { name: "Offline", body: "The city map stays usable without a connection." },
      { name: "Privacy", body: "Account optional. The map works without one." },
    ],
  },
  how: {
    title: "How it works",
    steps: [
      { n: "01", name: "Say where you're going", body: "Address, saved place, or just ask out loud." },
      { n: "02", name: "Pick your way", body: "Car, transit, walking or mixed: Shortcut compares time, cost and waiting." },
      { n: "03", name: "Arrive and park", body: "We take you to the spot, or to the right stop." },
    ],
  },
  cities: {
    kicker: "Where we are",
    title: "Starting in Turin",
    body: "Turin and its metro area are our first city: local data, local rules, local transit. Then we go elsewhere.",
    cta: "See the city plan",
  },
  waitlist: {
    title: "Join the waitlist",
    sub: "We launch next month. We'll email you the day the app goes live.",
    email: "Your email",
    city: "Your city",
    button: "Notify me at launch",
    success: "You're in. We'll write at launch.",
    duplicate: "You're already on the list. See you soon.",
    error: "Enter a valid email address.",
    failed: "Something went wrong. Please try again.",
    consent: "I agree to receive an email when Shortcut is available.",
    note: "No spam. One-click unsubscribe.",
    storeNote: "App Store and Google Play at launch",
  },
  faq: {
    title: "Frequently asked",
    items: [
      { q: "When does Shortcut launch?", a: "Next month on iOS and Android. Waitlist members get the link first." },
      { q: "What does it cost?", a: "Core navigation, transit and parking are free. Some advanced features will be part of a subscription." },
      { q: "Where does parking data come from?", a: "Garage operators, sensors and city open data, combined with our own models for curbside spots." },
      { q: "Do I need an account?", a: "No. An account only saves your places and syncs preferences." },
      { q: "What about my data?", a: "Only what's needed to navigate. We don't sell personal data. Details in the privacy policy." },
      { q: "Who is behind Shortcut?", a: "Shortcut is an app by Civimatica, working on urban data and mobility." },
    ],
  },
  cta: {
    title: "Ready to take the shortcut?",
    sub: "Leave your email and we'll ping you the moment it's on the stores.",
  },
  footer: {
    tagline: "One app to move through the city: parking, transit, driving and charging.",
    product: "Product",
    company: "Company",
    legal: "Legal",
    byline: "Shortcut is an app by",
    rights: "All rights reserved.",
    company_site: "civimatica.com",
  },
  cookies: {
    title: "Cookies and privacy",
    body: "We use essential cookies to run the site and, only with your consent, analytics cookies to understand what works.",
    accept: "Accept all",
    reject: "Essential only",
    more: "Privacy policy",
  },
  featuresPage: {
    title: "Everything Shortcut does",
    sub: "One map for parking, transit, driving, charging and micromobility.",
    items: [
      { name: "Curbside parking", body: "Zones with likelihood of a free spot, rules and tariffs, guidance to the street." },
      { name: "Garages", body: "Live free spaces, hourly price, max height and walking distance to your destination." },
      { name: "Car dimensions", body: "Save your car once: length, width, height. We only show spaces it fits in." },
      { name: "Corrected arrivals", body: "Predictions based on real vehicle data, not just the printed timetable." },
      { name: "Protected connections", body: "About to miss a connection? We hand you plan B before you get off." },
      { name: "Disruptions", body: "Closed stops, diversions, suspended lines: official and community reports." },
      { name: "Traffic-light countdowns", body: "Seconds to green on junctions we've mapped along your route." },
      { name: "Live traffic", body: "Coloured roads, incidents and jams, with automatic rerouting." },
      { name: "EV charging", body: "Chargers by plug, power, operator and availability — addable as a stop." },
      { name: "Voice assistant", body: "Ask questions and change your trip by talking, even while driving." },
      { name: "Micromobility", body: "Shared scooters and bikes on the same map." },
      { name: "Offline", body: "City map usable without a connection." },
    ],
    chips: ["2 spaces free", "Green in 12 s", "Connection saved"],
    lights: {
      kicker: "Traffic lights",
      title: "You know how long until green",
      body: "On the junctions we've mapped we show the seconds left until green: you pull away smoothly, brake less at the last second and burn less fuel.",
      points: [
        "Countdown on mapped junctions",
        "Speed hint to catch the green wave",
        "Fewer hard stops in traffic",
        "Works by voice, phone still in your pocket",
      ],
    },
    ev: {
      kicker: "Charging",
      title: "The right charger, not the nearest one",
      body: "We filter chargers by plug, power and operator, and tell you whether they're free right now. Add one to the trip as a stop, with the estimated battery on arrival.",
      points: [
        "Real availability and delivered power",
        "Charging stop inside the route",
        "Battery estimate at arrival",
        "Parking and charging compared together",
      ],
    },
    closing: {
      title: "One map, the whole city",
      body: "Join the list: we email you the day Shortcut is downloadable.",
    },
  },

  citiesPage: {
    title: "Turin first, then the rest",
    sub: "We build city by city, with each city's data.",
    body: "Moving through Turin means a strict street grid, restricted zones, arcades, hills and a transit network you have to read properly. We start here because it's the city we know best, then we repeat the model.",
    statusTitle: "City status",
    statusCols: ["City", "Status"],
    rows: [
      ["Turin", "First city at launch"],
      ["Turin metro area", "At launch"],
      ["Milan", "In preparation"],
      ["Other Italian cities", "On request"],
    ],
    askTitle: "Want Shortcut in your city?",
    askBody: "Put your city in the waitlist form: requests decide the order.",
  },
  downloadPage: {
    title: "Shortcut is coming",
    sub: "Launching next month on iPhone and Android. Join the list and be among the first.",
    storesTitle: "On the stores soon",
    reqTitle: "What you need",
    req: ["iPhone on iOS 16 or later", "Android 10 or later", "Location enabled while navigating", "Account optional"],
    chips: ["Launching next month", "Turin first", "No spam"],
    dayOne: {
      title: "What happens when you join",
      items: [
        { name: "The link, on day one", body: "One email when the app hits the stores. Not a newsletter in disguise." },
        { name: "Your city counts", body: "The cities people put in the list decide the order we open in after Turin." },
        { name: "No spam", body: "Email and city, nothing else. One-click unsubscribe, always." },
      ],
    },
    steps: {
      title: "How we get to launch",
      items: [
        { n: "01", name: "Turin first", body: "Local data, restricted zones, parking and the GTT network: the city we know best." },
        { n: "02", name: "Then the metro area", body: "The surrounding towns join with the same map and the same data." },
        { n: "03", name: "Other cities", body: "We open where demand is strongest. Outside Turin we're not live yet, and we say so." },
      ],
    },
    closing: {
      title: "See you at launch",
      body: "One email, the download link, and the city in your pocket.",
    },
  },

  privacy: {
    title: "Privacy policy",
    updated: "Last updated: August 2026",
    intro:
      "Shortcut is an app by Civimatica. This page explains in plain language what data we handle on this site and in the app.",
    sections: [
      { h: "What the site collects", p: "If you join the waitlist we store your email, the city you enter and the signup date. Nothing else." },
      { h: "Why", p: "Only to notify you at launch and to understand which cities to open next. We don't sell your data." },
      { h: "Cookies", p: "Essential cookies to run the site; analytics cookies only after your consent, which you can withdraw at any time." },
      { h: "Location in the app", p: "Location is used for navigation and processed on your device to compute routes. You can use the map without an account." },
      { h: "Your rights (GDPR)", p: "You can request access, rectification, deletion or portability of your data, and object to processing. We reply within 30 days." },
      { h: "Contact", p: "Data controller: Civimatica. Write to privacy@civimatica.com for any request." },
    ],
  },
  terms: {
    title: "Terms of service",
    updated: "Last updated: August 2026",
    intro: "Terms for using the Shortcut site and waitlist, operated by Civimatica.",
    sections: [
      { h: "The service", p: "Shortcut is an urban navigation app. This site presents the product and collects waitlist signups." },
      { h: "Fair use", p: "Don't use the site for unlawful activity, bulk signups or unauthorised access attempts." },
      { h: "Product information", p: "Features and launch dates may change. Information here is not a contractual commitment." },
      { h: "Responsibility", p: "Always follow traffic law. App guidance is support, not an instruction to manoeuvre." },
      { h: "Contact", p: "Any questions: hello@civimatica.com." },
    ],
  },
  notFound: { title: "Page not found", sub: "We lost this shortcut." },
};
